### ISSUE TITLE
Automate integration testing with pytest

### ISSUE THREAD

**Issue by matt6697** [virtualdesktopdevops/citrix-adc-frrouting-sync#1]
It would be nice to run integration testing  using pytest to check if network routes are correctly injected/withdrawed in frrouting for each test case.

**Comment by matt6697** [comment]
@jpmondet : Could you have a look on the test cases configured in https://github.com/virtualdesktopdevops/citrix-adc-frrouting-sync/blob/feature/daemonize/tests/integration/test_sync_daemon.py to check real life issues coverage.

**Comment by jpmondet** [comment]
> @jpmondet : Could you have a look on the test cases configured in https://github.com/virtualdesktopdevops/citrix-adc-frrouting-sync/blob/feature/daemonize/tests/integration/test_sync_daemon.py to check real life issues coverage.

It looks very good to me! 🙂 
 
I would maybe try to add multiple vips at the same time to see if the script & FRR can keep up correctly.  
Or try to artificially lock vtysh to see if the script can handle it gracefully.  
It would also be awesome to add another frr container to the mix to establish a tiny bgp peering just to make sure that the route(s) is(are) correctly advertised ^^  

While I'm here, I might be wrong but it looks like the comment on line 33 should say `goes down` instead of `goes up` ?

**Comment by matt6697** [comment]
Line 33 has been corrected : good point ;-)
  - [x] Try to add multiple vips at the same time to see if the script & FRR can keep up correctly.
  - [ ] Try to artificially lock vtysh to see if the script can handle it gracefully.

Route redistribution is tested in a disconnected lab environment with two ADC virtual machines and one FRR router simulating the L3 fabric router.

**Comment by matt6697** [comment]
Tried to run the sync daemon when having another vtysh cli open : route deletion works just after having manually added a sample route through vtysh. Running multiple vtysh clients doesn't sems to be a problem with frrouting 7.3.1. How can I "lock" vtysh ?

![image](https://user-images.githubusercontent.com/32440697/94949653-9215ff80-04e1-11eb-8074-6e7e1af23e99.png)

**Comment by jpmondet** [comment]
Oh, perfect !  

I'm a lil' confused on the locking part, the code still takes this into account  : https://github.com/FRRouting/frr/blob/4b40d5ffb0c34d4e99dd121085b46d4f4a896b72/lib/vty.c#L2577

And even `frr_reload.py` handle this case : https://github.com/FRRouting/frr/blob/4b40d5ffb0c34d4e99dd121085b46d4f4a896b72/tools/frr-reload.py#L118

Anyways, they certainly changed something but I wonder if it's intended ^^
